version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes_from:
      - data_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: termos
      MYSQL_DATABASE: termosdeuso

  data_database:
    image: cogniteev/echo
    command: echo 'Data Container for MySql'
    volumes:
      - /var/lib/mysql